### ISSUE TITLE
postProcessing error

### ISSUE THREAD

**Issue by reinhold-willcox** [TeamCOMPAS/COMPAS#457]
**Describe the bug**
Sometimes when I run the postProcessing.py file, I get the following error:
```
Checking if directory and files to combine exist
Combining csv files from subdirectories
Creating H5 file COMPAS_Output.h5
Traceback (most recent call last):
  File "postProcessing.py", line 550, in <module>
    h5Name=h5Name)
  File "postProcessing.py", line 95, in main
    createH5file(dataRootDir=dataRootDir, h5Name=h5Name, h5GroupDict=h5GroupDict) 
  File "postProcessing.py", line 324, in createH5file
    addHdf5Data(hf, group, combineFilePath)
  File "postProcessing.py", line 420, in addHdf5Data
    h5group[param][chunkBegin:chunkEnd] = np.array(data[:,iParam],dtype=dtype)
IndexError: too many indices for array
```

It has only shown up for me on ozstar, but I can't figure out how to consistently replicate it. The error seems to suggest that data does not have the shape to handle the [:, iParam] index, but this file works fine most of the time, which means data is usually the correct shape. Has anyone else run into this, or can offer a suggestion?

**Label the issue**
Please label the 'severity' and 'urgency' of this issue. You can choose:

`urgency_low`      - This issue is not urgent

`severity_moderate` - This is a moderately severe bug

**To Reproduce**
I'm not sure...

**Expected behavior**
The postprocessing file should produce the COMPAS_Output.h5. More ideally, the longterm solution is probably to produce the H5 directly from COMPAS, instead of the intermediary csv files. 

**Versioning (please complete the following information):**
 - OS: OzStar
 - COMPAS v02.17.04

**Additional context**

**Comment by reinhold-willcox** [comment]
COMPAS now outputs H5 files directly, closing this issue.
