### ISSUE TITLE
Docs failing (even on the dev branch)

### ISSUE THREAD

**Issue by avivajpeyi** [TeamCOMPAS/COMPAS#966]
The documentation builds seem to fail at times, even with no changes to the docs:

 
![Screenshot from 2023-05-11 10-06-47](https://github.com/TeamCOMPAS/COMPAS/assets/15642823/81d18914-a50e-4c47-938b-b6471822d711)

The latest dev branch build (as of 10AM, May 11th, NZ time):
https://readthedocs.org/projects/compas/builds/20585129/

Logs:
```
Build #20585129
latest ([bc97c0c683977d9b29a4bc3df834b8871f9c30d6](https://github.com/TeamCOMPAS/COMPAS/commit/bc97c0c683977d9b29a4bc3df834b8871f9c30d6))
Build failed
Error
We encountered a problem with a command while building your project. To resolve this error, double check your project configuration and installed dependencies are correct and have not changed recently.

git clone --no-single-branch --depth 50 https://github.com/TeamCOMPAS/COMPAS .
git checkout --force origin/dev
git clean -d -f -f
python3.8 -mvirtualenv $READTHEDOCS_VIRTUALENV_PATH
python -m pip install --upgrade --no-cache-dir pip setuptools
python -m pip install --upgrade --no-cache-dir pillow mock==1.0.1 alabaster>=0.7,<0.8,!=0.7.5 commonmark==0.9.1 recommonmark==0.5.0 sphinx sphinx-rtd-theme readthedocs-sphinx-ext<2.3
python -m pip install --upgrade --upgrade-strategy eager --no-cache-dir .[docs]
cat online-docs/conf.py
python -m sphinx -T -E -b html -d _build/doctrees -D language=en . $READTHEDOCS_OUTPUT/html
Running Sphinx v6.2.1
WARNING: Invalid configuration value found: 'language = None'. Update your configuration to a valid language code. Falling back to 'en' (English).

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/compas/envs/latest/lib/python3.8/site-packages/sphinx/registry.py", line 442, in load_extension
    mod = import_module(extname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/compas/envs/latest/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/docs/checkouts/readthedocs.org/user_builds/compas/envs/latest/lib/python3.8/site-packages/sphinx/builders/linkcheck.py", line 20, in <module>
    from requests import Response
  File "/home/docs/checkouts/readthedocs.org/user_builds/compas/envs/latest/lib/python3.8/site-packages/requests/__init__.py", line 43, in <module>
    import urllib3
  File "/home/docs/checkouts/readthedocs.org/user_builds/compas/envs/latest/lib/python3.8/site-packages/urllib3/__init__.py", line 38, in <module>
    raise ImportError(
ImportError: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with OpenSSL 1.0.2n  7 Dec 2017. See: https://github.com/urllib3/urllib3/issues/2168

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/compas/envs/latest/lib/python3.8/site-packages/sphinx/cmd/build.py", line 280, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "/home/docs/checkouts/readthedocs.org/user_builds/compas/envs/latest/lib/python3.8/site-packages/sphinx/application.py", line 225, in __init__
    self.setup_extension(extension)
  File "/home/docs/checkouts/readthedocs.org/user_builds/compas/envs/latest/lib/python3.8/site-packages/sphinx/application.py", line 404, in setup_extension
    self.registry.load_extension(self, extname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/compas/envs/latest/lib/python3.8/site-packages/sphinx/registry.py", line 445, in load_extension
    raise ExtensionError(__('Could not import extension %s') % extname,
sphinx.errors.ExtensionError: Could not import extension sphinx.builders.linkcheck (exception: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with OpenSSL 1.0.2n  7 Dec 2017. See: https://github.com/urllib3/urllib3/issues/2168)

Extension error:
Could not import extension sphinx.builders.linkcheck (exception: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with OpenSSL 1.0.2n  7 Dec 2017. See: https://github.com/urllib3/urllib3/issues/2168)
Command time: 0s Return: 2
```

**Comment by avivajpeyi** [comment]
@yuzhesong  found some related issues:

https://github.com/readthedocs/readthedocs.org/issues/10290
https://github.com/urllib3/urllib3/issues/2168

**Comment by ilyamandel** [comment]
Unfortunately, we may have to leave this one until @jeffriley is back...

**Comment by jeffriley** [comment]
I can't  look at this until I get back in early June. I did not change
anything, so either changes we've made on github have broken this, or
readthedocs has changed and we need to do something.

**Comment by ilyamandel** [comment]
I think it's on the github end (see 
"urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with OpenSSL 1.0.2n  7 Dec 2017. See: https://github.com/urllib3/urllib3/issues/2168 "), so I don't think it's urgent for us to fix -- can wait until you are back, Jeff.

**Comment by jeffriley** [comment]
I can look when I get back - but was the change to openssl recent, and is
it necessary? And was it a change we made? i.e. if readthedocs won't work
with openssl can we go back?

**Comment by avivajpeyi** [comment]
I can also look at this as Jeff is away -- it might just need some updates to the `.readthedocs.yaml` file. 

Ideally --  this will just sort itself out! 😄 I assume other folks using readthedocs + github are also facing this issue (and looks like there is a "bounty" to fix the SSL issue!! haha)

BTW is there a specific reason we use read-the-docs to build the documentation? 

It is possible to use GitHub actions to build and deploy sphinx pages (see https://github.com/marketplace/actions/sphinx-docs-to-github-pages). The nice thing about this is that it does not require a login to read-the-docs; everything can be controlled via a github workflow. 


Only downside is that the documentation URL will have to change (eg instead of the pages being on https://compas.readthedocs.io/en/latest/, they could be hosted at https://compas.science/docs)

**Comment by jeffriley** [comment]
We use readthedocs because that's what I knew of at the time - I had never
used it but it was easy to pick up. I'm happy to move to sphinx deployed by
github if that's easy to do.

**Comment by avivajpeyi** [comment]
Closing the read-the-docs folks have fixed this on their end
